language: cpp


before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .travis/install_dependencies_osx.sh ; fi
  - mkdir build
  - cd build
  - cmake ..

script:
  - make VERBOSE=1
  - make tests && make test

after_script:
  - ./dublin-traceroute

matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      compiler: gcc
    - os: osx
      osx_image: xcode11
      compiler: gcc

addons:
  homebrew:
    # packages are installed in install_dependencies_osx.sh because libtins
    # needs to be installed from sources on older osx versions, because they
    # have old versions in binary form.
    update: true

# GitHub project metadata
project:
  name: insomniacslk/dublin-traceroute
  version: 1.0
  description: Dublin Traceroute is a NAT-aware multipath tracerouting tool

    # Commands to prepare for build_command
  #build_command_prepend: ./configure

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
  build_command:
    - mkdir build
      cd build
      cmake ..
      make

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "g++" ]; then export CXXFLAGS="-stdlib=libc++"; fi